// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: keyvalueclerk.proto

package KeyValue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MapServiceClerkClient is the client API for MapServiceClerk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapServiceClerkClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
}

type mapServiceClerkClient struct {
	cc grpc.ClientConnInterface
}

func NewMapServiceClerkClient(cc grpc.ClientConnInterface) MapServiceClerkClient {
	return &mapServiceClerkClient{cc}
}

func (c *mapServiceClerkClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/KeyValueClerk.MapServiceClerk/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapServiceClerkClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/KeyValueClerk.MapServiceClerk/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapServiceClerkClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, "/KeyValueClerk.MapServiceClerk/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapServiceClerkServer is the server API for MapServiceClerk service.
// All implementations must embed UnimplementedMapServiceClerkServer
// for forward compatibility
type MapServiceClerkServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	mustEmbedUnimplementedMapServiceClerkServer()
}

// UnimplementedMapServiceClerkServer must be embedded to have forward compatible implementations.
type UnimplementedMapServiceClerkServer struct {
}

func (UnimplementedMapServiceClerkServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMapServiceClerkServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedMapServiceClerkServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedMapServiceClerkServer) mustEmbedUnimplementedMapServiceClerkServer() {}

// UnsafeMapServiceClerkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapServiceClerkServer will
// result in compilation errors.
type UnsafeMapServiceClerkServer interface {
	mustEmbedUnimplementedMapServiceClerkServer()
}

func RegisterMapServiceClerkServer(s grpc.ServiceRegistrar, srv MapServiceClerkServer) {
	s.RegisterService(&MapServiceClerk_ServiceDesc, srv)
}

func _MapServiceClerk_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceClerkServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KeyValueClerk.MapServiceClerk/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceClerkServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapServiceClerk_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceClerkServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KeyValueClerk.MapServiceClerk/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceClerkServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapServiceClerk_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceClerkServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KeyValueClerk.MapServiceClerk/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceClerkServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapServiceClerk_ServiceDesc is the grpc.ServiceDesc for MapServiceClerk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapServiceClerk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KeyValueClerk.MapServiceClerk",
	HandlerType: (*MapServiceClerkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MapServiceClerk_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _MapServiceClerk_Put_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _MapServiceClerk_Append_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keyvalueclerk.proto",
}
